version: '2'
services:
  link:
    build: .
    volumes:
      - ./:/go/src/github.com/Scalingo/link
    ports:
      - 1313:1313
    cap_add:
      - NET_ADMIN
    network_mode: 'host'
    environment:
      ETCD_HOSTS: http://172.17.0.1:22379
      INTERFACE: eth10
      USER: link
      PASSWORD: password
    command: reflex -r '\.go$$' -s -- sh -c 'go install -race && /go/bin/link'
  etcd:
    volumes:
      - ./docker/etcd:/data/etcd
    image: quay.io/coreos/etcd:v3.2.11
    command: etcd --name etcd-cluster --data-dir /data/etcd --listen-client-urls http://0.0.0.0:2379 --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://172.17.0.1:22379
    ports:
      - 22379:2379

