dependencies = []
description = "LinK is a networking agent that will let multiple hosts share a virtual IP."
destination_server = ["app-hosting-node", "database-hosting-node", "internal"]
flags = ["cli", "deployed-by-chef", "tools"]
languages = ["go"]
owner = "john@scalingo.com"
team = "IST"
version = "1.1.0"
